[project]
name = "python-library-atividade"
version = "0.1.0"
description = ""
authors = [
    {name = "itsthoda",email = "mo4na12000@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard] (>=0.134.0,<0.135.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
